### ISSUE TITLE
Reinit menu

### ISSUE THREAD

**Issue by levipadre** [alizahid/slinky#33]
Hi,

Thanks for the plugin, it's great.

Is there a way to re-init the destroyed menu?
Here you created a destroy method: https://github.com/alizahid/slinky/issues/16
I need it for mobile as well (only mobile).
So a need to switch between normal menu and Slinky one.
What I did:
```
const menu = $('#menu').slinky({resize: false});
```
when you switch to desktop:
```
menu.destroy();
```
and when you go back to mobile and try to reinit to the required level, that doesn't work:
```
menu.jump('.active-level');
```
neither
```
menu.home();
```

Thank you.

**Comment by alizahid** [comment]
If you destroy Slinky, you need to re init, too.

After `menu.destroy()`, be sure to call `const menu = $('#menu').slinky()` again.

Then you can use `jump` or `home`, etc.

**Comment by levipadre** [comment]
I made a Codepen show how I need to achieve:
https://codepen.io/anon/pen/pLXbJB

**Comment by levipadre** [comment]
Please don't close the ticket. I really need this.

**Comment by alizahid** [comment]
@levipadre Sorry! I was writing a snippet to help you, but then I got pulled into something. Let me get back to you soon.

**Comment by levipadre** [comment]
Any luck, maybe?

**Comment by alizahid** [comment]
First, sorry for the incredible delay in reply.

But the fix is quite easy!

Slinky uses `.active` as the default jump to point when you initialize the menu. And because you were trying to manually navigate there, it was causing a conflict.

I've forked your pen here https://codepen.io/anon/pen/ZdNJWZ

The only change was adding a new class `foo` to the active element and you can safely navigate there without seeing this bug.
